# 06 D2L 课堂逐步操作
实际教材：https://zh.d2l.ai/chapter_installation/index.html

两名学生分别运行、展示输出后再推进。此Notebook是课堂代码记录，不代替教材安装章和官方Notebook。基础张量代码只依赖torch；完整教材安装还需另外验证`from d2l import torch as d2l`。
第2.1节为必做；自动微分、线性训练、MLP为接力内容。玩具回归仅用于检查训练，不是HiMCM研究数据。

## 环境核对
先猜结果，再运行；两人各解释一句。

In [1]:
import sys
import torch
print(sys.executable)
print(torch.__version__)

/Users/szy/miniconda3/envs/HiMCM/bin/python
2.14.0


## D2L §2.1：创建张量
先猜结果，再运行；两人各解释一句。

In [2]:
x = torch.arange(12)
print(x)
print(x.shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])


## D2L §2.1：改变形状
先猜结果，再运行；两人各解释一句。

In [3]:
X = x.reshape(3, 4)
print(X)
print(X.shape, X.numel())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4]) 12


## D2L §2.1：运算与索引
先猜结果，再运行；两人各解释一句。

In [4]:
print(X + 1)
print(X[0])
print(X.sum())

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([0, 1, 2, 3])
tensor(66)


## D2L §2.5：自动微分（有余力时）
先猜结果，再运行；两人各解释一句。

In [5]:
x = torch.arange(4.0, requires_grad=True)
y = 2 * torch.dot(x, x)
y.backward()
print(y.item())
print(x.grad)

28.0
tensor([ 0.,  4.,  8., 12.])


## 教学简化：线性回归准备
先猜结果，再运行；两人各解释一句。

In [6]:
from torch import nn
x = torch.linspace(0, 1, 20).reshape(-1, 1)
y = 2 * x + 1
torch.manual_seed(0)
model = nn.Linear(1, 1)
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

## 教学简化：训练循环
先猜结果，再运行；两人各解释一句。

In [7]:
losses = []
for epoch in range(400):
    optimizer.zero_grad()
    loss = loss_fn(model(x), y)
    loss.backward()
    optimizer.step()
    losses.append(loss.item())
print(model.weight.item(), model.bias.item())

1.996064305305481 1.0021216869354248


## 图：实际训练结果
先猜结果，再运行；两人各解释一句。

In [8]:
import matplotlib.pyplot as plt
fig, axes = plt.subplots(1, 2, figsize=(11, 3.7))
axes[0].plot(losses, color='#117e80', linewidth=2.5)
axes[0].set(xlabel='Epoch', ylabel='MSE loss', title='Actual training loss')
axes[0].set_yscale('log')
axes[1].scatter(x.detach().numpy(), y.detach().numpy(), label='Teaching data', color='#5374a5')
with torch.no_grad():
    prediction = model(x)
axes[1].plot(x.detach().numpy(), prediction.numpy(), color='#117e80', label='Trained prediction', linewidth=2.5)
axes[1].set(xlabel='x', ylabel='y', title='Known rule: y = 2x + 1')
axes[1].legend(frameon=False)
for ax in axes:
    ax.spines[['top', 'right']].set_visible(False)
    ax.grid(alpha=0.12)
fig.tight_layout()
plt.show()

## MLP前向计算：没有训练
先猜结果，再运行；两人各解释一句。

In [9]:
net = nn.Sequential(nn.Linear(3, 8), nn.ReLU(), nn.Linear(8, 1))
print(net(torch.zeros(2, 3)).shape)

torch.Size([2, 1])
